//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeSharp {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExchangeSharpResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExchangeSharpResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeSharp.Properties.Resources.ExchangeSharpResources", typeof(ExchangeSharpResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; throwExceptions=&quot;false&quot; internalLogToConsole=&quot;false&quot; internalLogToConsoleError=&quot;false&quot; internalLogLevel=&quot;Trace&quot;&gt;
        ///  &lt;targets&gt;
        ///    &lt;target name=&quot;logfile&quot; xsi:type=&quot;File&quot; fileName=&quot;logfile.txt&quot; archiveNumbering=&quot;Sequence&quot; archiveEvery=&quot;Day&quot; maxArchiveFiles=&quot;28&quot; encoding=&quot;UTF-8&quot;/&gt;
        ///    &lt;!--&lt;target name=&quot;console&quot; xsi:type=&quot;Console&quot; layout= &quot;$[${date:format=yyyy-MM-dd HH\:mm\:s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NLog_config {
            get {
                return ResourceManager.GetString("NLog_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coin,WithdrawalFieldsAllowed
        ///1CR,0
        ///ABY,0
        ///AC,0
        ///ACH,0
        ///ADN,0
        ///AEON,0
        ///AERO,0
        ///AIR,0
        ///AMP,1
        ///APH,0
        ///ARCH,0
        ///ARDR,1
        ///AUR,0
        ///AXIS,0
        ///BALLS,0
        ///BANK,0
        ///BBL,0
        ///BBR,0
        ///BCC,0
        ///BCH,1
        ///BCN,0
        ///BCY,1
        ///BDC,0
        ///BDG,0
        ///BELA,1
        ///BITCNY,0
        ///BITS,0
        ///BITUSD,0
        ///BLK,1
        ///BLOCK,0
        ///BLU,0
        ///BNS,0
        ///BONES,0
        ///BOST,0
        ///BTC,1
        ///BTCD,1
        ///BTCS,0
        ///BTM,0
        ///BTS,0
        ///BURN,0
        ///BURST,1
        ///C2,0
        ///CACH,0
        ///CAI,0
        ///CC,0
        ///CCN,0
        ///CGA,0
        ///CHA,0
        ///CINNI,0
        ///CLAM,1
        ///CNL,0
        ///CNMT,0
        ///CNOTE,0
        ///COMM,0
        ///CON,0
        ///CORG,0
        ///CRYPT,0
        ///CURE,0
        ///CVC,1
        ///CYC,0
        ///DAO,0
        ///DASH,1
        ///DCR,1
        ///DGB,1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PoloniexWithdrawalFields {
            get {
                return ResourceManager.GetString("PoloniexWithdrawalFields", resourceCulture);
            }
        }
    }
}
